version: 2.1

orbs:
  aws-ecs: circleci/aws-ecs@1.1.0

jobs:
  test_and_build_jar:
    working_directory: ~/location-service
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: location-service-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: location-service-{{ checksum "pom.xml" }}
      - run: mvn clean package
      - run: echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
      - run: docker build -t kshitijbahul/location-service:$CIRCLE_SHA1 .
      - run: docker push kshitijbahul/location-service:$CIRCLE_SHA1
  tag_buit_image:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
      - run: docker pull kshitijbahul/location-service:$CIRCLE_SHA1
      - run: docker image tag kshitijbahul/location-service:$CIRCLE_SHA1 kshitijbahul/location-service:$CIRCLE_TAG
      - run: docker push kshitijbahul/location-service:$CIRCLE_TAG

workflows:
  version: 2.1
  build_and_push:
    jobs:
      - test_and_build_jar
      - aws-ecs/deploy-service-update:
          requires:
            - test_and_build_jar
          family: location-service-task
          cluster-name: location-service-cluster-2
          container-image-name-updates: 'container=location-service-container,tag=${CIRCLE_SHA1}'

    promote_build_to_test:
      jobs:
        - tag_buit_image:
            filters:
              tags:
                only: /^test.*/
              branches:
                ignore: /.*/
        - aws-ecs/deploy-service-update:
            filters:
              tags:
                only: /^test.*/
              branches:
                ignore: /.*/
            requires:
              - tag_buit_image
            family: location-service-task
            cluster-name: location-service-cluster-2
            container-image-name-updates: 'container=location-service-container,tag=${CIRCLE_TAG}'





