version: 2.1

orbs:
  maven: circleci/maven@1.0.1

#workflows:
#  maven_test:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results
jobs:
  test_and_build_jar:
    working_directory: ~/location-service
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: location-service-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: location-service-{{ checksum "pom.xml" }}
      - run: mvn clean package
      - run: echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
      - run: docker build -t kshitijbahul/location-service:$CIRCLE_SHA1 .
      - run: docker push kshitijbahul/location-service:$CIRCLE_SHA1
      - persist_to_workspace:
          root: ~/location-service/
          paths:
            - Dockerfile
            - target/location-service.jar
  #create_docker_image:
    #steps:

workflows:
  version: 2.1
  build_and_push:
    jobs:
      - test_and_build_jar





#obs:
# #build_docker_image:
# build:
#   working_directory: ~/location-service
#   docker:
#     - image: circleci/openjdk:8-jdk-stretch
#     - checkout
#     - restore_cache:
#         key:
#         - location-service-{{ checksum "pom.xml" }}
#     - run: mvn dependency:go-offline
#     - save_cache:
#         paths:
#           - ~/.m2
#         key: location-service-{{ checksum "pom.xml" }}
#     - run: mvn clean package
#     - store_artifacts
#       - path: target/location-service.jar
#     - run : docker build -t kshitijbahul/location-service:$CIRCLE_BUILD_NUM



