version: 2.1

orbs:
  maven: circleci/maven@1.0.1
  aws-ecs: circleci/aws-ecs@1.1.0

#workflows:
#  maven_test:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results
jobs:
  test_and_build_jar:
    working_directory: ~/location-service
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: location-service-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: location-service-{{ checksum "pom.xml" }}
      - run: mvn clean package
      - save_cache:
          paths:
            - ~/location-service/
          key: location-service-{{ checksum "pom.xml" }}
      - run: echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
      - run: docker build -t kshitijbahul/location-service:$CIRCLE_SHA1 .
      - run: docker push kshitijbahul/location-service:$CIRCLE_SHA1
      - persist_to_workspace:
          root: ~/location-service/
          paths:
            - Dockerfile
            - target/location-service.jar
  tag_buit_image:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
      - run: docker image tag kshitijbahul/location-service:$CIRCLE_SHA1 kshitijbahul/location-service:$CIRCLE_TAG
      - run: docker push kshitijbahul/location-service:$CIRCLE_TAG
  #create_docker_image:
    #steps:

workflows:
  version: 2.1
  build_and_push:
    jobs:
      - test_and_build_jar
      - aws-ecs/deploy-service-update:
          requires:
            - test_and_build_jar
          family: location-service-task
          cluster-name: location-service-cluster-2
          container-image-name-updates: 'container=location-service-container,tag=${CIRCLE_SHA1}'
  promote_build:
    jobs:
      - tag_buit_image:
          filters:
            tags:
              only: /.*/
      - aws-ecs/deploy-service-update:
          filters:
            tags:
              only: /^test.*/
          requires:
            - tag_buit_image
          family: location-service-task
          cluster-name: location-service-cluster-2
          container-image-name-updates: 'container=location-service-container,tag=${$CIRCLE_TAG}'





#obs:
# #build_docker_image:
# build:
#   working_directory: ~/location-service
#   docker:
#     - image: circleci/openjdk:8-jdk-stretch
#     - checkout
#     - restore_cache:
#         key:
#         - location-service-{{ checksum "pom.xml" }}
#     - run: mvn dependency:go-offline
#     - save_cache:
#         paths:
#           - ~/.m2
#         key: location-service-{{ checksum "pom.xml" }}
#     - run: mvn clean package
#     - store_artifacts
#       - path: target/location-service.jar
#     - run : docker build -t kshitijbahul/location-service:$CIRCLE_BUILD_NUM



