version: 2.1

orbs:
  maven: circleci/maven@1.0.1

#workflows:
#  maven_test:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results
jobs:
  build_image:
    working_directory: ~/location-service
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: location-service-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: location-service-{{ checksum "pom.xml" }}
      - run: mvn clean package
      - persist_to_workspace:
          root: ~/location-service/target
          paths:
            - /location-service.jar

workflows:
  version: 2.1
  build_and_push:
    jobs:
      - build_image





#obs:
# #build_docker_image:
# build:
#   working_directory: ~/location-service
#   docker:
#     - image: circleci/openjdk:8-jdk-stretch
#     - checkout
#     - restore_cache:
#         key:
#         - location-service-{{ checksum "pom.xml" }}
#     - run: mvn dependency:go-offline
#     - save_cache:
#         paths:
#           - ~/.m2
#         key: location-service-{{ checksum "pom.xml" }}
#     - run: mvn clean package
#     - store_artifacts
#       - path: target/location-service.jar
#     - run : docker build -t kshitijbahul/location-service:$CIRCLE_BUILD_NUM



